name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # application.yml 파일을 생성하는 단계
    - name: Create application.yml
      run: |
        echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml

    # jdk 17을 설치하는 단계
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # gradle 패키지를 캐시하는 단계
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # jdk 버전을 확인하는 단계
    - name: Verify JDK version
      run: java -version

    # gradle을 사용하여 프로젝트를 빌드하는 단계
    - name: Build with Gradle
      run: ./gradlew build

    # 테스트를 실행하는 단계
    - name: Run tests
      run: ./gradlew test

    # 테스트 결과를 아티팩트로 저장하는 단계
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results/test

    # 빌드 결과를 아티팩트로 저장하는 단계
    - name: Archive build artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs
